name: Releases

on:
  push:
    tags:
    - '*'

jobs:
  needs: build-windows
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - uses: ncipollo/release-action@v1
      with:
        artifacts: ${{needs.build-windows.outputs.artifact_id}}